# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQB0Cdux-7gmugV1oaCtmML4dOaOf1cd
"""

from fastapi import FastAPI
from pydantic import BaseModel

import pickle
import numpy as np

app = FastAPI()

model = pickle.load(open("model.pkl","rb"))
scaler = pickle.load(open("scaler.pkl","rb"))

class InputData(BaseModel):

    features:list

@app.get("/")
def home():

    return {"status":"SVM API Running"}

@app.post("/predict")
def predict(data: InputData):

    try:
        print("=== REQUEST MASUK ===")
        print(data.features)

        x = np.array(data.features).reshape(1, -1)
        print("Array:", x.shape)

        x = scaler.transform(x)
        print("Scaler OK")

        prediction = model.predict(x)[0]
        print("Predict OK")

        probability = model.predict_proba(x).max()
        print("Probability OK")

        return {
            "prediction": int(prediction),
            "probability": float(probability)
        }

    except Exception as e:
        import traceback

        traceback.print_exc()

        return {
            "error": str(e)
        }
